version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: detailed

cache:
  - '%USERPROFILE%\.nuget\packages -> paket.lock'

artifacts:
  - path: '**\Release\*.nupkg'

build_script:
  - cmd: dotnet build -c Release

deploy:
  - provider: NuGet
    api_key:
      secure: aTOF8Ct1vcSWfpJ2IzbM/k+qMLMJaGxnHTTcDS2cxditHNtm4BJeVSxYx3PB7J1M
    on:
      appveyor_repo_tag: true
